; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[version]
build_flags = !python build_defines.py

[env:espwroom32]
platform = espressif32
board = upesy_wroom
framework = arduino
build_flags = 
	-Wall
	-Wunused
	;-Wno-address-of-packed-member
	-O3
	-DNDEBUG
;data_folder = data
board_build.filesystem = littlefs    ; use littlefs instead of spiffs, default is spiffs
board_build.partitions = default.csv ; use default 4Mb partition scheme, 2*1.2MB for app and 1.375MB for filesystem
;board_build.ldscript = eagle.flash.4m.ld
upload_port = COM3
upload_speed = 921600
targets = upload
lib_deps = FS
;lib_deps = akkoyun/MD5@^1.0.0
monitor_speed = 57600
